---
# Activate scene "god_natt" at 00:30
- id: bedtime
  alias: "Läggdags"
  trigger:
    - platform: time
      at: 00:30:00
  action:
    - service: scene.turn_on
      entity_id:
        - scene.god_natt


# Notify when porch door opens when no one is home
- id: notify_when_porch_door_opens
  alias: "Notifiering att altandörr öppnades"
  trigger:
    - entity_id: binary_sensor.altandorr_sensor
      from: 'off'
      platform: state
      to: 'on'
  condition:
    - condition: state
      entity_id: group.all_devices
      state: 'not_home'
  action:
    - data:
        message: "Altandörren öppnandes trots att ingen är hemma"
        title: "Altandörr öppen"
      service: notify.PUSHBULLET


# Notify when front door opens when no one is home
- id: notify_when_front_door_opens
  alias: "Notifiering att ytterdörr öppnades"
  trigger:
    - entity_id: binary_sensor.ytterdorr_sensor
      from: 'off'
      platform: state
      to: 'on'
  condition:
    - condition: state
      entity_id: group.all_devices
      state: 'not_home'
  action:
    - data:
        message: "Ytterdörren öppnades trots att ingen är hemma"
        title: "Ytterdörr öppen"
      service: notify.PUSHBULLET


# Notify when movement is registered in stairway when no one is home
- id: notify_at_movement_in_stairway
  alias: "Notifiering vid rörelse i trapp"
  trigger:
    - entity_id: binary_sensor.trapp_sensor
      from: 'off'
      platform: state
      to: 'on'
  condition:
    - condition: state
      entity_id: group.all_devices
      state: 'not_home'
  action:
    - service: notify.PUSHBULLET
      data:
        message: "Rörelse i trappen trots att ingen är hemma"
        title: "Rörelse i trapp"


# Turn on stairway lights when movement is registered
- id: turn_on_stairway_lightning_at_movement
  alias: "Tänd trappbelysning vid rörelse"
  trigger:
    - entity_id: binary_sensor.trapp_sensor
      from: 'off'
      platform: state
      to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.trapp_luminance
      below: 5
  action:
    - service: light.turn_on
      entity_id: light.trappbelysning
      data:
        brightness: 25
        color_name: white


# Turn off stairway lights when movement is no longer registered
- id: turn_off_stairway_lightning_at_no_movement
  alias: "Släck trappbelysning vid ingen rörelse"
  trigger:
    - entity_id: binary_sensor.trapp_sensor
      from: 'on'
      platform: state
      to: 'off'
  condition:
    - condition: state
      entity_id: light.trappbelysning
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.trappbelysning


# Turn on outdoor lighting at sunset
- id: outdoor_lighting_at_sunset
  alias: "Tänd utebelysning vid solnedgång"
  trigger:
    - platform: sun
      event: sunset
  action:
    - service: homeassistant.turn_on
      entity_id:
        - group.outdoor_lighting


# Turn on window and accent lighting when lux is below 5
- id: window_and_accent_lighting_when_lux_is_low
  alias: "Tänd fönster och accentbelysning när lux är under 5"
  trigger:
    - platform: numeric_state
      entity_id: sensor.trapp_luminance
      below: 5
    - platform: state
      entity_id: group.all_devices
      from: 'not_home'
      to: 'home'
  condition:
    - condition: state
      entity_id: group.all_devices
      state: 'home'
    - condition: numeric_state
      entity_id: sensor.trapp_luminance
      below: 5
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id:
        - group.window_lighting
        - group.accent_lighting


# Turn on window lighting at sunset when no one is home
- id: window_lighting_at_sunset_when_no_one_is_home
  alias: "Tänd fönsterbelysning vid solnedgång när ingen är hemma"
  trigger:
    - platform: sun
      event: sunset
  condition:
    - condition: state
      entity_id: group.all_devices
      state: 'not_home'
  action:
    - service: homeassistant.turn_on
      entity_id:
        - group.window_lighting
