---
homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Stockholm

  customize:
    switch.hallampa_switch:
      friendly_name: Hallampa
    media_player.roku_1ws3al012963:
      friendly_name: Roku
    light.taklampor:
      homebridge_hidden: true
      hidden: true
    light.utebelysning:
      homebridge_hidden: true
      hidden: true
    binary_sensor.trapp_sensor:
      friendly_name: Trapp
      device_class: motion
    binary_sensor.altandorr_sensor:
      friendly_name: Altandörr
      device_class: opening
    binary_sensor.ytterdorr_sensor:
      friendly_name: Ytterdörr
      device_class: opening
    sensor.trapp_luminance:
      hidden: false
    sensor.cpu_temperatur:
      homebridge_hidden: true
    sensor.yr_temperature:
      homebridge_hidden: true

  customize_domain:
    switch:
      icon: mdi:lightbulb
    media_player:
      homebridge_hidden: true
    device_tracker:
      homebridge_hidden: true

  customize_glob:
    "sensor.patriks*":
      hidden: true
    "sensor.annas*":
      hidden: true
    "sensor.ipad*":
      hidden: true
    "sensor.trapp*":
      hidden: true
    "sensor.ytterdorr*":
      hidden: true
    "sensor.altandorr*":
      hidden: true

frontend:
config:
conversation:
history:
  exclude:
    entities:
      - sensor.mot_alvangen
logbook:
  exclude:
    entities:
      - sensor.mot_alvangen
logger:
  default: critical
  logs:
    homeassistant.components.rfxtrx: info
sun:
updater:
ios:
  push:
    categories:
      - name: Släck lampor
        identifier: 'EVENING_ACCENT_LIGHTS'
        actions:
          - identifier: 'TURN_OFF_LIGHTS'
            title: 'Ja'
            activationMode: 'background'
            authenticationRequired: 'no'
            destructive: 'no'
            behavior: 'default'
discovery:
  ignore:
    - roku
    - plex_mediaserver

recorder:
  db_url: !secret recorder_db_url
http:
  api_password: !secret http_api_password
influxdb:
  host: !secret influxdb_host
tts:
  platform: google
rfxtrx:
  device: /dev/ttyUSB0
zwave:
  usb_path: /dev/ttyUSB20
tradfri:
  host: !secret tradfri_host
  api_key: !secret tradfri_api_key
mqtt:
  broker: !secret mqtt_broker
  port: 1883
  client_id: !secret mqtt_client_id
  username: !secret mqtt_username
  password: !secret mqtt_password
ifttt:
  key: !secret ifttt_key
notify:
  - name: Pushover
    platform: pushover
    api_key: !secret notify_pushover_api_key
    user_key: !secret notify_pushover_user_key


group: !include groups.yaml
scene: !include scenes.yaml
automation: !include automations.yaml
zone: !include zones.yaml


sensor:
  - platform: yr
    monitored_conditions:
      - temperature
      - windSpeed
  - platform: vasttrafik
    key: !secret sensor_vasttrafik_key
    secret: !secret sensor_vasttrafik_secret
    departures:
      - name: Mot älvängen
        from: Albotorget, Ale
        heading: Älvängen resecentrum, Ale
  - platform: command_line
    name: CPU Temperatur
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ (value | multiply(0.001)) | round(1) }}'
  - platform: rfxtrx
    devices:
      0A520A0016010072370179:
        name: Utomhus

switch:
  - platform: rfxtrx
    signal_repetitions: 2
    devices:
      0b1100f8009963220c010f60:
        name: Vind

      # GDR2 A-2
      7100a0041020000:
        name: Trebenslampa

      # GDR2 A-3
      7100a0041030000:
        name: Ljusbollar

      # GDR2 A-4
      7100a0041040000:
        name: Kristallampa

      # GDR2 B-2
      7100a0042020000:
        name: Fönster i kök

      # GDR2 B-3
      7100a0042030000:
        name: Fönster i gästrum

      # GDR2 B-4
      7100a0042040000:
        name: Fönster i sovrum

      # GDR2 C-1
      7100a0043010000:
        name: Månlampa

      # GDR2 C-2
      7100a0043020000:
        name: Fönster i Eiras rum

      0b1100030001010201040f70:
        name: Altan

      0b1100030001010101040f70:
        name: Framsida

device_tracker:
  - platform: tomato
    host: !secret device_tracker_tomato_host
    username: !secret device_tracker_tomato_username
    password: !secret device_tracker_tomato_password
    http_id: !secret device_tracker_tomato_http_id
    interval_seconds: 600
    consider_home: 1900
    track_new_devices: 'no'
  - platform: owntracks

# media_player:
#   - platform: roku
#   - platform: plex
#   - platform: spotify
#     client_id: !secret media_player_spotify_client_id
#     client_secret: !secret media_player_spotify_secret

light:
  - platform: limitlessled
    bridges:
      - host: !secret light_limitlessled_host
        port: 5987
        groups:
          - number: 1
            name: Trappbelysning
            type: rgbww
            fade: 'on'

binary_sensor:
  platform: rfxtrx
  devices:
    0b1100030001010101040f70:
      name: Dörrklocka

input_boolean:
  guest_mode:
    name: Gästläge
    initial: 'off'
    icon: mdi:account-multiple
  sleep_mode:
    name: Sovläge
    initial: 'off'
    icon: mdi:hotel
  alarm_mode:
    name: Larmläge
    initial: 'off'
    icon: mdi:alarm-light
