---
homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Stockholm

  customize:
    switch.hallampa_switch:
      friendly_name: Hallampa
    media_player.roku_1ws3al012963:
      friendly_name: Roku
    light.taklampor:
      emulated_hue_hidden: true
      homebridge_hidden: true
      google_assistant: false
      hidden: true
    light.utelampor:
      emulated_hue_hidden: true
      homebridge_hidden: true
      google_assistant: false
      hidden: true
    light.utebelysning:
      emulated_hue_hidden: true
      homebridge_hidden: true
      google_assistant: false
      hidden: true
    binary_sensor.trapp_sensor:
      friendly_name: Trapp
      device_class: motion
    binary_sensor.altandorr_sensor:
      friendly_name: Altandörr
      device_class: opening
      icon: mdi:door
    binary_sensor.ytterdorr_sensor:
      friendly_name: Ytterdörr
      device_class: opening
      icon: mdi:door
    sensor.trapp_luminance:
      hidden: false
    sensor.cpu_temperatur:
      homebridge_hidden: true
    sensor.yr_temperature:
      homebridge_hidden: true
    sensor.trapp_battery:
      hidden: false
    sensor.ytterdorr_battery:
      hidden: false
    sensor.altandorr_battery:
      hidden: false
    sensor.tradfri_remote_control:
      friendly_name: Trådfri fjärrkortroll
      icon: mdi:battery
    sensor.tradfri_wireless_dimmer:
      friendly_name: Trådfri dimmer
      icon: mdi:battery
    sensor.tradfri_motion_sensor:
      friendly_name: Trådfri rörelsesensor
      icon: mdi:battery
    sensor.stomne_vagtemperatur:
      icon: mdi:road-variant
    sensor.stomne_lufttemperatur:
      icon: mdi:thermometer
    group.all_automations:
      hidden: false

    sensor.pollen_gras:
      friendly_name: Gräs
      icon: mdi:flower

    sensor.pollen_hassel:
      friendly_name: Hassel
      icon: mdi:flower

    sensor.pollen_al:
      friendly_name: Al
      icon: mdi:leaf

    sensor.pollen_salg_vide:
      friendly_name: Sälg / vide
      icon: mdi:leaf

    sensor.pollen_grabo:
      friendly_name: Gråbo
      icon: mdi:flower

    sensor.pollen_bok:
      friendly_name: Bok
      icon: mdi:leaf

    sensor.pollen_alm:
      friendly_name: Alm
      icon: mdi:leaf

    sensor.pollen_bjork:
      friendly_name: Björk
      icon: mdi:leaf

    sensor.pollen_ek:
      friendly_name: Ek
      icon: mdi:flower

    group.default_view:
      order: 1

    group.floors:
      order: 2

    group.monitoring:
      order: 3

    group.media_players:
      order: 4

    group.misc:
      order: 5

  customize_domain:
    switch:
      icon: mdi:lightbulb
      google_assistant_type: light
    media_player:
      homebridge_hidden: true
    device_tracker:
      hidden: true
      homebridge_hidden: true

  customize_glob:
    "sensor.*_battery":
      icon: mdi:battery
    "sensor.patriks*":
      hidden: true
    "sensor.annas*":
      hidden: true
    "sensor.ipad*":
      hidden: true
    "sensor.trapp*":
      hidden: true
    "sensor.ytterdorr*":
      hidden: true
    "sensor.altandorr*":
      hidden: true


###########
# LOGGING #
###########

history:
  exclude:
    entities:
      - sensor.mot_alvangen
      - device_tracker.annas_iphone
      - device_tracker.owntracks_patrik
logbook:
  exclude:
    entities:
      - sensor.mot_alvangen
logger:
  default: warn


############
# SERVICES #
############

frontend:
config:
conversation:
sun:
updater:
ios:
discovery:
recorder:
  db_url: !secret recorder_db_url
http:
  api_password: !secret http_api_password
influxdb:
  host: !secret influxdb_host
tts:
  platform: google
  language: sv
rfxtrx:
  device: /dev/ttyUSB0
zwave:
  autoheal: false
  usb_path: /dev/ttyAMA0
mqtt:
  broker: !secret mqtt_broker
  port: 1883
  client_id: !secret mqtt_client_id
  username: !secret mqtt_username
  password: !secret mqtt_password
ifttt:
  key: !secret ifttt_key
google_assistant:
  project_id: !secret google_assistant_project_id
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  api_key: !secret google_assistant_api_key
  exposed_domains:
    - switch
    - light
cloud:
  google_actions:
    filter:
      include_domains:
        - switch
        - light
      include_entities:
        - group.accent_lights
        - group.evening_lights
        - group.outdoor_lights
        - group.window_lights
emulated_hue:
  expose_by_default: true
  exposed_domains:
    - light
    - switch
telegram_bot:
  - platform: polling
    api_key: !secret notify_telegram_api_key
    allowed_chat_ids:
      - !secret notify_telegram_chat_id_1
      - !secret notify_telegram_chat_id_2
tradfri:
  host: !secret tradfri_host
  allow_tradfri_groups: false
panel_iframe:
  grafana:
    title: 'Grafana'
    icon: mdi:elevation-rise
    # yamllint disable-line rule:line-length
    url: 'https://grafana.sundhall.se/dashboard/db/hemovervakning?refresh=1m&orgId=1&theme=light&kiosk=true'
  nodered_flows:
    title: 'Node-RED'
    icon: mdi:nodejs
    url: 'https://nodered.sundhall.se'


############
# ENTITIES #
############

group: !include_dir_merge_named groups
scene: !include_dir_merge_list scenes
automation: !include_dir_merge_list automations
zone: !include_dir_merge_list zones
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
light: !include_dir_merge_list lights
notify: !include_dir_merge_list notifications
device_tracker: !include_dir_merge_list device_trackers
media_player: !include_dir_merge_list media_players
input_boolean: !include_dir_merge_named input_booleans
