---
homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Stockholm

  customize:
    switch.hallampa_switch:
      friendly_name: Hallampa
    media_player.roku_1ws3al012963:
      friendly_name: Roku
    light.taklampor:
      emulated_hue_hidden: true
      homebridge_hidden: true
      google_assistant: false
      hidden: true
    light.utelampor:
      emulated_hue_hidden: true
      homebridge_hidden: true
      google_assistant: false
      hidden: true
    light.utebelysning:
      emulated_hue_hidden: true
      homebridge_hidden: true
      google_assistant: false
      hidden: true
    binary_sensor.trapp_sensor:
      friendly_name: Trapp
      device_class: motion
    binary_sensor.altandorr_sensor:
      friendly_name: Altandörr
      device_class: opening
    binary_sensor.ytterdorr_sensor:
      friendly_name: Ytterdörr
      device_class: opening
    sensor.trapp_luminance:
      hidden: false
    sensor.cpu_temperatur:
      homebridge_hidden: true
    sensor.yr_temperature:
      homebridge_hidden: true
    sensor.trapp_battery:
      hidden: false
    sensor.ytterdorr_battery:
      hidden: false
    sensor.altandorr_battery:
      hidden: false

  customize_domain:
    switch:
      icon: mdi:lightbulb
      google_assistant_type: light
    media_player:
      homebridge_hidden: true
    device_tracker:
      homebridge_hidden: true

  customize_glob:
    "sensor.patriks*":
      hidden: true
    "sensor.annas*":
      hidden: true
    "sensor.ipad*":
      hidden: true
    "sensor.trapp*":
      hidden: true
    "sensor.ytterdorr*":
      hidden: true
    "sensor.altandorr*":
      hidden: true


###########
# LOGGING #
###########

history:
  exclude:
    entities:
      - sensor.mot_alvangen
logbook:
  exclude:
    entities:
      - sensor.mot_alvangen
logger:
  default: warn


############
# SERVICES #
############

frontend:
config:
conversation:
map:
sun:
updater:
ios:
discovery:
recorder:
  db_url: !secret recorder_db_url
http:
  api_password: !secret http_api_password
influxdb:
  host: !secret influxdb_host
tts:
  platform: google
  language: sv
rfxtrx:
  device: /dev/ttyUSB0
zwave:
  usb_path: /dev/ttyUSB20
mqtt:
  broker: !secret mqtt_broker
  port: 1883
  client_id: !secret mqtt_client_id
  username: !secret mqtt_username
  password: !secret mqtt_password
ifttt:
  key: !secret ifttt_key
google_assistant:
  project_id: !secret google_assistant_project_id
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  api_key: !secret google_assistant_api_key
  exposed_domains:
    - switch
    - light
emulated_hue:
  expose_by_default: true
  exposed_domains:
    - light
    - switch
telegram_bot:
  - platform: polling
    api_key: !secret notify_telegram_api_key
    allowed_chat_ids:
      - !secret notify_telegram_chat_id_1
      - !secret notify_telegram_chat_id_2


############
# ENTITIES #
############

group: !include_dir_merge_named groups
scene: !include_dir_merge_list scenes
automation: !include_dir_merge_list automations
zone: !include_dir_merge_list zones
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
light: !include_dir_merge_list lights
notify: !include_dir_merge_list notifications
device_tracker: !include_dir_merge_list device_trackers
media_player: !include_dir_merge_list media_players
input_boolean: !include_dir_merge_named input_booleans
