---
- platform: tomato
  host: !secret device_tracker_tomato_host
  username: !secret device_tracker_tomato_username
  password: !secret device_tracker_tomato_password
  http_id: !secret device_tracker_tomato_http_id
  interval_seconds: 600
  consider_home: 1900
  track_new_devices: 'no'
